# Generated by Django 3.2.25 on 2025-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_artwork_sku'),
        ('profiles', '0002_remove_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='artworks.Artwork'),
        ),
    ]
