# Generated by Django 3.2.25 on 2025-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
