# Generated by Django 3.2.25 on 2025-01-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artworks.Category'),
        ),
    ]
