# Generated by Django 3.2.25 on 2025-01-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20250120_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
